apiVersion: lifecycle.keptn.sh/v1alpha2
kind: KeptnEvaluationProvider
metadata:
  name: prometheus
  namespace: otel-demo
spec:
  targetServer: "http://prometheus-kube-prometheus-prometheus.default.svc.cluster.local:9090"